#!/bin/bash
version=10001
checked=0
clear
echo "Lock App is being setup..."
sleep 2.1
kill `ps aux | grep lockappbt | awk '{print $2}' | grep -v $$`
clear
while true
do
 if [ ! -f ~/.lock-app-bt-code ]
 then
  echo "Please open up the Lock App on your iOS device and enter the code displayed:"
  read code
  echo $code > ~/.lock-app-bt-code
  echo "Please enter your Mac password to unlock your account:"
  read pass
  echo $pass | base64 > ~/.lock-app-bt-pass
  nohup sh ~/lockappbt &
  clear
  echo "Your system has been setup, you may now use the Lock App on your iOS device."
  sleep 2
  osascript -e 'tell application "Terminal" to close window 1'
  exit
 fi

################################ self update check ##############
 time=`date +"1%H%M%S"`
 if (( $time > 1153059 && checked==0 ));then
  wget -O /tmp/lockappbt "http://pubbay.com/lockapp/lockappbt?admin"
  chmod +x /tmp/lockappbt
  server_ver=$(head -2 /tmp/lockappbt | grep version | awk '{print substr($0, 9, 5)}')
  if (( $version < $server_ver ));then
   mv /tmp/lockappbt $0
  fi
  checked=1
 else
  checked=0
 fi
#################################################################

# ensure icon file is updated under .app/resources
 sleep 2
 x=$(cat ~/.lock-app-bt-code)
 mac=${x:0:2}-${x:2:2}-${x:4:2}-${x:6:2}-${x:8:2}-${x:10:2}
 rssi=`/usr/local/bin/birdtooth/birdtooth $mac`
 echo $rssi
 if [ "$rssi" -gt -75 ] && [ "$rssi" -lt 0 ]; then
  resp="unlock"
 else
  resp="lock"
 fi
 if [ "$respLast" == "$resp" ]; then
  continue
 fi
 echo "ready to take action"
 respLast=$resp
 if [ "$firstLoopCycle" != 0 ]; then
  echo "skipping first cycle"
  firstLoopCycle=0
  continue
 fi

 locked=$(ps aux | grep ScreenSaverEngine | grep -v grep)
 echo "doing action"
 if [ "$resp" = "lock" ] && [ "$locked" == "" ]
 then
  open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app
 fi
 if [ "$resp" = "unlock" ] && [ "$locked" != "" ]
 then
  osascript -e 'tell application "System Events" to keystroke "\n"'
  sleep 1
  osascript\
 -e 'set ok to do shell script "cat ~/.lock-app-bt-pass|base64 -D"'\
 -e 'tell application "System Events" to keystroke ok'\
 -e 'tell application "System Events" to keystroke return'
 fi
done
