#!/bin/bash

echo 'IyEvYmluL2Jhc2gKdmVyc2lvbj0xMDAwMgpjaGVja2VkPTAKY2xlYXIKZWNobyAiTG9jayBBcHAgaXMgYmVpbmcgc2V0dXAuLi4iCnNsZWVwIDIuMQpraWxsIGBwcyBhdXggfCBncmVwIGxvY2thcHAgfCBhd2sgJ3twcmludCAkMn0nIHwgZ3JlcCAtdiAkJGAKY2xlYXIKd2hpbGUgdHJ1ZQpkbwogaWYgWyAhIC1mIH4vLmxvY2stYXBwLWNvZGUgXQogdGhlbgogIGVjaG8gIlBsZWFzZSBvcGVuIHVwIHRoZSBMb2NrIEFwcCBvbiB5b3VyIGlPUyBkZXZpY2UgYW5kIGVudGVyIHRoZSBjb2RlIGRpc3BsYXllZDoiCiAgcmVhZCBjb2RlCiAgZWNobyAkY29kZSA+IH4vLmxvY2stYXBwLWNvZGUKICBlY2hvICJQbGVhc2UgZW50ZXIgeW91ciBNYWMgcGFzc3dvcmQgdG8gdW5sb2NrIHlvdXIgYWNjb3VudDoiCiAgcmVhZCBwYXNzCiAgZWNobyAkcGFzcyB8IGJhc2U2NCA+IH4vLmxvY2stYXBwLXBhc3MKICBub2h1cCBzaCAvdXNyL2xvY2FsL2Jpbi9sb2NrYXBwICYKICBjbGVhcgogIGVjaG8gIllvdXIgc3lzdGVtIGhhcyBiZWVuIHNldHVwLCB5b3UgbWF5IG5vdyB1c2UgdGhlIExvY2sgQXBwIG9uIHlvdXIgaU9TIGRldmljZS4iCiAgc2xlZXAgMgogIG9zYXNjcmlwdCAtZSAndGVsbCBhcHBsaWNhdGlvbiAiVGVybWluYWwiIHRvIGNsb3NlIHdpbmRvdyAxJwogIGV4aXQKIGZpCgojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyBzZWxmIHVwZGF0ZSBjaGVjayAjIyMjIyMjIyMjIyMjIwogdGltZT1gZGF0ZSArIjElSCVNJVMiYAogaWYgKCggJHRpbWUgPiAxMTUzMDU5ICYmIGNoZWNrZWQ9PTAgKSk7dGhlbgogIHdnZXQgLU8gL3RtcC9sb2NrYXBwICJodHRwOi8vcHViYmF5LmNvbS9sb2NrYXBwL2xvY2thcHA/YWRtaW4iCiAgY2htb2QgK3ggL3RtcC9sb2NrYXBwCiAgc2VydmVyX3Zlcj0kKGhlYWQgLTIgL3RtcC9sb2NrYXBwIHwgZ3JlcCB2ZXJzaW9uIHwgYXdrICd7cHJpbnQgc3Vic3RyKCQwLCA5LCA1KX0nKQogIGlmICgoICR2ZXJzaW9uIDwgJHNlcnZlcl92ZXIgKSk7dGhlbgogICBtdiAvdG1wL2xvY2thcHAgJDAKICBmaQogIGNoZWNrZWQ9MQogZWxzZQogIGNoZWNrZWQ9MAogZmkKIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMKCiByZXNwPSQoY3VybCAtcyAiaHR0cDovL3B1YmJheS5jb20vbG9ja2FwcC8/YWRtaW4mdXVpZD0kY29kZSIpCiBlY2hvICRyZXNwCiBpZiBbICIkcmVzcCIgPSAibG9jayIgXQogdGhlbgogIG9wZW4gL1N5c3RlbS9MaWJyYXJ5L0ZyYW1ld29ya3MvU2NyZWVuU2F2ZXIuZnJhbWV3b3JrL1ZlcnNpb25zL0EvUmVzb3VyY2VzL1NjcmVlblNhdmVyRW5naW5lLmFwcAogZmkKIGlmIFsgIiRyZXNwIiA9ICJ1bmxvY2siIF0KIHRoZW4KICBvc2FzY3JpcHQgLWUgJ3RlbGwgYXBwbGljYXRpb24gIlN5c3RlbSBFdmVudHMiIHRvIGtleXN0cm9rZSAiXG4iJwogIHNsZWVwIC4zCiAgb3Nhc2NyaXB0XAogLWUgJ3NldCBvayB0byBkbyBzaGVsbCBzY3JpcHQgImNhdCB+Ly5sb2NrLWFwcC1wYXNzfGJhc2U2NCAtRCInXAogLWUgJ3RlbGwgYXBwbGljYXRpb24gIlN5c3RlbSBFdmVudHMiIHRvIGtleXN0cm9rZSBvaydcCiAtZSAndGVsbCBhcHBsaWNhdGlvbiAiU3lzdGVtIEV2ZW50cyIgdG8ga2V5c3Ryb2tlIHJldHVybicKIGZpCiBzbGVlcCAxCmRvbmUK'|base64 -D> ~/lockapp

echo 'IyEvYmluL2Jhc2gKc3UgLSAkMSAtYyAibm9odXAgfi9sb2NrYXBwICYiCg=='|base64 -D> ~/lockapp-wrapper

chmod +x ~/lockapp*
sudo defaults write com.apple.loginwindow LoginHook ~/lockapp-wrapper
rm ~/.lock-app-code ~/.lock-app-pass
osascript\
 -e 'tell application "Terminal"'\
 -e 'activate'\
 -e 'do script "sh ~/lockapp"'\
 -e 'end tell'
